// utils.js

// Array of pet care quotes
const petCareQuotes = [
  "Caring for a pet is not a duty, it’s a privilege.",
  "The best care for your pet is built on love and patience.",
  "A healthy pet is a happy home.",
  "Pets don’t need perfection, just consistent care.",
  "Pet care is self-care—for when they thrive, so do we.",
  "A little grooming, a lot of love.",
  "Happiness is a well-fed, well-loved pet.",
  "Love them as family, care for them as family.",
  "Pet care is not seasonal—it’s lifelong.",
  "The smallest act of care can mean the world to your pet.",
  "Walks are not just exercise, they’re memories in the making.",
  "Groom your dog, and you’ll groom happiness.",
  "Every wagging tail is a sign of care well given.",
  "Training your dog is training yourself in patience.",
  "The best toy for a dog is a caring owner.",
  "Dogs spell love with food, care, and time.",
  "A brushed coat is a dog’s smile in disguise.",
  "A cared-for dog knows no loneliness.",
  "To a dog, care is measured in belly rubs and gentle words.",
  "Treats fade, care lasts.",
  "Cats don’t ask for much—just food, space, and endless love.",
  "A brushed cat is a happy cat.",
  "Scratch posts save couches, but care saves hearts.",
  "A well-fed cat is a poem in motion.",
  "Give them time, and cats give you trust.",
  "Cat care is patience, quiet, and gentle respect.",
  "A cared-for cat turns houses into homes.",
  "Love your cat, and they’ll love you—on their terms.",
  "Good care turns meows into purrs.",
  "Cat care is the art of balance—freedom and love.",
  "A bird’s song is the reward of gentle care.",
  "Clean cages, happy wings.",
  "Caring for a bird is giving music to your home.",
  "The brighter the feathers, the deeper the care.",
  "A cared-for bird flies on trust, not fear.",
  "Gentle hands raise happy wings.",
  "Bird care is patience—freedom within safety.",
  "Feed them well, and their song will thank you.",
  "Birds measure care in seed and safety.",
  "A bird cared for is a melody that never fades.",
  "Clear water, calm minds.",
  "Caring for fish is caring for peace itself.",
  "A clean tank is love in action.",
  "Fish don’t bark or purr, but they shine under your care.",
  "The calm of the aquarium reflects the calm of the caregiver.",
  "Care for their water, and they’ll care for your soul.",
  "Fish care is balance—clarity, patience, and consistency.",
  "Even silence speaks when the tank is thriving.",
  "Every ripple is gratitude for your care.",
  "Happy fish make tranquil homes.",
  "Hamsters, rabbits, guinea pigs—small pets, big love.",
  "Little paws deserve great care.",
  "Tiny pets need mighty responsibility.",
  "Caring for the small teaches us about the big.",
  "A rabbit’s hop is joy created by care.",
  "Every squeak is a thank you for love.",
  "Small cages, big responsibilities.",
  "Little pets, endless happiness.",
  "The size of your pet doesn’t measure the depth of care.",
  "Gentle care, gentle souls.",
  "Caring for pets is the purest form of unconditional love.",
  "A pet’s trust is the greatest reward for good care.",
  "You can’t buy loyalty, but you can earn it through care.",
  "Caring for a pet is caring for your heart.",
  "Every act of care builds an unbreakable bond.",
  "Pets give us love; we give them care.",
  "To love a pet is to commit to lifelong care.",
  "In caring for pets, we learn to care for life itself.",
  "The world is kinder when pets are cared for.",
  "Care is love in action.",
  "Clean pets, happy homes.",
  "Grooming is more than beauty—it’s health.",
  "A bath today prevents trouble tomorrow.",
  "Shiny coats are a reflection of care.",
  "Good care prevents pain, poor care creates it.",
  "Health is the true beauty of pets.",
  "Love your pet enough to check their health.",
  "Brushing teeth is as important as brushing coats.",
  "A cared-for body equals a happy spirit.",
  "Regular care is better than emergency repair.",
  "Good food, good life—for pets too.",
  "Nutrition is love served in a bowl.",
  "Feed them well, love them better.",
  "Every healthy meal adds years of joy.",
  "Balanced diets create balanced lives.",
  "Care is measured in meals as well as cuddles.",
  "Treats are fine, but nutrition is forever.",
  "Food is fuel; love is the driver.",
  "Healthy food, healthy hearts.",
  "Feeding is caring.",
  "Caring for pets is caring for the Earth’s gentlest souls.",
  "Pet care is a promise kept daily.",
  "Compassion is the foundation of pet care.",
  "To care for a pet is to practice kindness daily.",
  "Responsible care is the truest form of love.",
  "A cared-for pet reflects the character of its owner.",
  "The joy of pets is multiplied by the care they receive.",
  "Pet care is not work—it’s devotion.",
  "In the eyes of a pet, care equals love.",
  "Care today builds memories tomorrow."
];

// Function to get a random pet care quote
function getRandomPetCareQuote() {
  const randomIndex = Math.floor(Math.random() * petCareQuotes.length);
  return petCareQuotes[randomIndex];
}

module.exports = { getRandomPetCareQuote };
